### ISSUE TITLE
运行一段时间会报错 不知道为什么？

### ISSUE THREAD

**Issue by jinwyp** [yihong0618/tg_bot_collections#10]
错误信息

···

Dec 15 15:53:48 grcsg9 python[1377994]:   File "/root/github/tg_bot_collections/venv/lib/python3.10/site-packages/telebot/util.py", line 147, in raise_exceptions
Dec 15 15:53:48 grcsg9 python[1377994]:     raise self.exception_info
Dec 15 15:53:48 grcsg9 python[1377994]:   File "/root/github/tg_bot_collections/venv/lib/python3.10/site-packages/telebot/util.py", line 90, in run
Dec 15 15:53:48 grcsg9 python[1377994]:     task(*args, **kwargs)
Dec 15 15:53:48 grcsg9 python[1377994]:   File "/root/github/tg_bot_collections/venv/lib/python3.10/site-packages/telebot/__init__.py", line 6801, in _run_middlewares_and_handler
Dec 15 15:53:48 grcsg9 python[1377994]:     result = handler['function'](message)
Dec 15 15:53:48 grcsg9 python[1377994]:   File "/root/github/tg_bot_collections/tg.py", line 239, in gemini_handler
Dec 15 15:53:48 grcsg9 python[1377994]:     m = message.text.strip().split(maxsplit=1)[1].strip()
Dec 15 15:53:48 grcsg9 python[1377994]: IndexError: list index out of range

···

**Comment by frostming** [comment]
拉最新代码先

**Comment by yihong0618** [comment]
@jinwyp 原因是我们之前用空格 split 的，有时候 user 会不打空格，最新代码解决这个问题了
