### ISSUE TITLE
使用setup.sh安装运行错误

### ISSUE THREAD

**Issue by nfervor** [yihong0618/tg_bot_collections#14]
使用setup.sh 安装完成后，systemctl status tgbotyh 查看状态如下。

● tgbotyh.service - tgbotyh service
     Loaded: loaded (/lib/systemd/system/tgbotyh.service; disabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sun 2023-12-17 13:59:34 CST; 27s ago
    Process: 653520 ExecStart=/root/tg_bot_collections/venv/bin/python /root/tg_bot_collections/tg.py XXXXXXXXXXXXX (code=exited, status>
   Main PID: 653520 (code=exited, status=1/FAILURE)
        CPU: 37ms

Dec 17 13:59:34 racknerd-fd7bca systemd[1]: tgbotyh.service: Main process exited, code=exited, status=1/FAILURE
Dec 17 13:59:34 racknerd-fd7bca systemd[1]: tgbotyh.service: Failed with result 'exit-code'.

发送消息给bot无响应，telegrambot应该是没有运行。

使用 /root/tg_bot_collections/venv/bin/python3 /root/tg_bot_collections/tg.py P6AiuURGQBLsj4zzA 运行后如下报错。

Traceback (most recent call last):
  File "/root/tg_bot_collections/tg.py", line 3, in <module>
    from telebot import TeleBot
ModuleNotFoundError: No module named 'telebot'

**Comment by jinwyp** [comment]
这个应该是python3的环境造成的 没有成功安装依赖库

你用的什么系统? 

目前linux 例如Ubuntu 或 centos 9  预装的是python3.6 


建议手动安装python3.10 (不要安装3.11, 推荐安装3.9或3.10) 安装完毕后重新创建venv虚拟环境 
具体进行如下操作

1. 删除项目目录下的 python3 虚拟环境目录
···
cd tg_bot_collections
rm -rf ./venv
···
2.  查看一下 python3或python3.10 路径 并记录下该路径
例如 
如果是使用系统默认的python3 请使用 ``` which python3  ```
如果是使用自己安装的python3.10 请使用 ``` which python3.10  ```

3. 重新创建 python3 虚拟环境目录 
例如 
如果是使用系统默认的python3 请使用 ``` /usr/bin/python3 -m venv "venv"  ```
如果是使用自己安装的python3.10 请使用 ``` /usr/local/bin/python3.10 -m venv "venv"  ```

注意/usr/bin/python3  路径要使用第二步上面的python版本的路径 自己修改一下 上面的命令路径

4. 激活虚拟环境  运行命令 ``` source venv/bin/activate
5. 安装项目依赖库 运行命令 ``` pip install -r requirements.txt ```

6. 退出虚拟环境 运行命令 ``` deactivate ```
7. 手动编辑一下系统服务 使用vi 编辑器或其他编辑 例如运行命令 ``` vi /lib/systemd/system/tgbotyh.service ```
把 ExecStart= 这行的 python3 路径 改为 python3.10的路径 例如 把 /usr/bin/python3 改为 /usr/local/bin/python3.10 然后保存退出

8. 重新装载systemd服务 运行 ``` sudo systemctl daemon-reload ```
9. 启动程序运行 ``` sudo systemctl restart tgbotyh.service ```

10. 查看是否运行正常 运行 systemctl status tgbotyh 查看日志

**Comment by nfervor** [comment]
系统是ubuntu 22.04，
root@racknerd-fd7bca:~/tg_bot_collections/venv/bin# python3 --version
Python 3.10.12

使用手动安装运行模式，可以正常运行。
python3 tg.py ${telegram_bot_token}

**Comment by yihong0618** [comment]
@nfervor 可以先手动使用 nohup 运行

**Comment by nfervor** [comment]
好的。thx

**Comment by jinwyp** [comment]
> 系统是ubuntu 22.04， root@racknerd-fd7bca:~/tg_bot_collections/venv/bin# python3 --version Python 3.10.12
> 
> 使用手动安装运行模式，可以正常运行。 python3 tg.py ${telegram_bot_token}


原因是 python3 有多个版本在linux 系统上  你用setup.sh 安装默认用的 系统默认的python3 版本  位置是、/usr/bin/python

而python3.10 是你手动安装的python3 版本 位置是 /usr/local/python3.10  

手动安装的结果和setup.sh 安装的依赖库安装的路径在不同的版本下面

具体解决方法就是按照上面的第7步开始往下做 改成python3.10 的路径就可以了

手动编辑一下系统服务 使用vi 编辑器或其他编辑 例如运行命令 vi /lib/systemd/system/tgbotyh.service
把 ExecStart= 这行的 python3 路径 改为 python3.10的路径 例如 把 /usr/bin/python3 改为 /usr/local/bin/python3.10 然后保存退出


具体可以看这篇文章解释
https://frostming.com/2019/03-13/where-do-your-packages-go/

**Comment by jinwyp** [comment]
项目更新了 支持了 修改python3的运行路径了.

只要在.env里面指定 Python_Bin_Path 的路径为/usr/local/bin/python3.10   在运行 setup.sh 就可以了 .

**Comment by nfervor** [comment]
多谢，晚些时候试一下。

Jin ***@***.***>于2023年12月19日 周二17:20写道：
