### ISSUE TITLE
ModuleNotFoundError: No module named 'telegramify_markdown'

### ISSUE THREAD

**Issue by ccinoo** [yihong0618/tg_bot_collections#23]
大佬，请问拉取最新代码并pip install后出现如下报错，该如何解决？

`Traceback (most recent call last):
  File "/root/tg_bot_collections/tg.py", line 4, in <module>
    from handlers import list_available_commands, load_handlers
  File "/root/tg_bot_collections/handlers/__init__.py", line 13, in <module>
    import telegramify_markdown
ModuleNotFoundError: No module named 'telegramify_markdown'
2024-03-21 09:14:02 - tg.py has been started.
Traceback (most recent call last):
  File "/root/tg_bot_collections/tg.py", line 4, in <module>
    from handlers import list_available_commands, load_handlers
  File "/root/tg_bot_collections/handlers/__init__.py", line 13, in <module>
    import telegramify_markdown
ModuleNotFoundError: No module named 'telegramify_markdown'
2024-03-21 09:15:02 - tg.py has been started.
Traceback (most recent call last):
  File "/root/tg_bot_collections/tg.py", line 4, in <module>
    from handlers import list_available_commands, load_handlers
  File "/root/tg_bot_collections/handlers/__init__.py", line 13, in <module>
    import telegramify_markdown
ModuleNotFoundError: No module named 'telegramify_markdown'

2024-03-21 09:16:02 - tg.py has been started.
Traceback (most recent call last):
  File "/root/tg_bot_collections/tg.py", line 4, in <module>
    from handlers import list_available_commands, load_handlers
  File "/root/tg_bot_collections/handlers/__init__.py", line 13, in <module>
    import telegramify_markdown
ModuleNotFoundError: No module named 'telegramify_markdown'`

**Comment by yihong0618** [comment]
pip install telegramify-markdown
python -m pip install telegramify-markdown

**Comment by ccinoo** [comment]
> pip install telegramify-markdown python -m pip install telegramify-markdown

好像之前已经安装过，不是这个原因？
`
[root@host tg_bot_collections]# python -m pip install --upgrade pip
WARNING: Ignoring invalid distribution -ip (/usr/local/python3.9/lib/python3.9/site-packages)
Requirement already satisfied: pip in /usr/local/python3.9/lib/python3.9/site-packages (24.0)
WARNING: Ignoring invalid distribution -ip (/usr/local/python3.9/lib/python3.9/site-packages)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[root@host tg_bot_collections]# python -m pip install --upgrade pip --force-reinstall
WARNING: Ignoring invalid distribution -ip (/usr/local/python3.9/lib/python3.9/site-packages)
Collecting pip
  Using cached pip-24.0-py3-none-any.whl.metadata (3.6 kB)
Using cached pip-24.0-py3-none-any.whl (2.1 MB)
WARNING: Ignoring invalid distribution -ip (/usr/local/python3.9/lib/python3.9/site-packages)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.0
    Uninstalling pip-24.0:
      Successfully uninstalled pip-24.0
  WARNING: The scripts pip, pip3 and pip3.9 are installed in '/usr/local/python3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-24.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[root@host tg_bot_collections]# pip install telegramify-markdown
WARNING: Ignoring invalid distribution -ip (/usr/local/python3.9/lib/python3.9/site-packages)
Requirement already satisfied: telegramify-markdown in /usr/local/python3.9/lib/python3.9/site-packages (0.1.2)
Requirement already satisfied: mistletoe>=1.3.0 in /usr/local/python3.9/lib/python3.9/site-packages (from telegramify-markdown) (1.3.0)
Requirement already satisfied: pytelegrambotapi>=4.16.1 in /usr/local/python3.9/lib/python3.9/site-packages (from telegramify-markdown) (4.16.1)
Requirement already satisfied: emoji>=2.10.1 in /usr/local/python3.9/lib/python3.9/site-packages (from telegramify-markdown) (2.10.1)
Requirement already satisfied: requests in /usr/local/python3.9/lib/python3.9/site-packages (from pytelegrambotapi>=4.16.1->telegramify-markdown) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/python3.9/lib/python3.9/site-packages (from requests->pytelegrambotapi>=4.16.1->telegramify-markdown) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/python3.9/lib/python3.9/site-packages (from requests->pytelegrambotapi>=4.16.1->telegramify-markdown) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/python3.9/lib/python3.9/site-packages (from requests->pytelegrambotapi>=4.16.1->telegramify-markdown) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/python3.9/lib/python3.9/site-packages (from requests->pytelegrambotapi>=4.16.1->telegramify-markdown) (2023.11.17)
WARNING: Ignoring invalid distribution -ip (/usr/local/python3.9/lib/python3.9/site-packages)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[root@host tg_bot_collections]# python -m pip install telegramify-markdown
WARNING: Ignoring invalid distribution -ip (/usr/local/python3.9/lib/python3.9/site-packages)
Requirement already satisfied: telegramify-markdown in /usr/local/python3.9/lib/python3.9/site-packages (0.1.2)
Requirement already satisfied: mistletoe>=1.3.0 in /usr/local/python3.9/lib/python3.9/site-packages (from telegramify-markdown) (1.3.0)
Requirement already satisfied: pytelegrambotapi>=4.16.1 in /usr/local/python3.9/lib/python3.9/site-packages (from telegramify-markdown) (4.16.1)
Requirement already satisfied: emoji>=2.10.1 in /usr/local/python3.9/lib/python3.9/site-packages (from telegramify-markdown) (2.10.1)
Requirement already satisfied: requests in /usr/local/python3.9/lib/python3.9/site-packages (from pytelegrambotapi>=4.16.1->telegramify-markdown) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/python3.9/lib/python3.9/site-packages (from requests->pytelegrambotapi>=4.16.1->telegramify-markdown) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/python3.9/lib/python3.9/site-packages (from requests->pytelegrambotapi>=4.16.1->telegramify-markdown) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/python3.9/lib/python3.9/site-packages (from requests->pytelegrambotapi>=4.16.1->telegramify-markdown) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/python3.9/lib/python3.9/site-packages (from requests->pytelegrambotapi>=4.16.1->telegramify-markdown) (2023.11.17)
WARNING: Ignoring invalid distribution -ip (/usr/local/python3.9/lib/python3.9/site-packages)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
`
`2024-03-21 09:42:01 - tg.py has been started.
Traceback (most recent call last):
  File "/root/tg_bot_collections/tg.py", line 4, in <module>
    from handlers import list_available_commands, load_handlers
  File "/root/tg_bot_collections/handlers/__init__.py", line 13, in <module>
    import telegramify_markdown
ModuleNotFoundError: No module named 'telegramify_markdown'`

**Comment by ccinoo** [comment]
奇怪，现在是出现以下报错了。GOOGLE_GEMINI_KEY设置了没用，还需要设置OPENAI_API_KEY吗？
`2024-03-21 10:03:02 - tg.py has been started.
Arg parse done.
Traceback (most recent call last):
  File "/root/tg_bot_collections/tg.py", line 48, in <module>
    main()
  File "/root/tg_bot_collections/tg.py", line 39, in main
    load_handlers(bot, options.disable_commands)
  File "/root/tg_bot_collections/handlers/__init__.py", line 106, in load_handlers
    module = importlib.import_module(f".{name}", __package__)
  File "/usr/local/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/tg_bot_collections/handlers/yi.py", line 16, in <module>
    client = OpenAI(
  File "/root/tg_bot_collections/gemini/lib/python3.9/site-packages/openai/_client.py", line 98, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable`

**Comment by yihong0618** [comment]
OPENAI_API_KEY 是 Yi 的如果你不用 YI
你需要随便 export 个
export OPENAI_API_KEY="avb"

**Comment by ccinoo** [comment]
> OPENAI_API_KEY 是 Yi 的如果你不用 YI 你需要随便 export 个 export OPENAI_API_KEY="avb"

这样可以了，谢谢。

**Comment by yihong0618** [comment]
不客气
