### ISSUE TITLE
代理问题

### ISSUE THREAD

**Issue by zhaoxin111** [yihong0618/tg_bot_collections#32]
您好，感谢分享。
我看代码中没有涉及代理的代码，国内网络不用代理没法访问telegram的，网上找了一下可以通过apihelper来设置，
`apihelper.proxy = {
    'http': 'socks5://login:pass@127.0.0.1:9000',
    'https':'socks5://login:pass@127.0.0.1:9000'
    }`
我是这么写的，但还是链接不上，不知道为什么，麻烦您指点一下，谢谢！

**Comment by yihong0618** [comment]
你得保证你的 terminal 能连代理，这里 socks5 是不行的，你得转成http

**Comment by zhaoxin111** [comment]
感谢指点，我删掉了代码中代理，然后设置了终端代理，现在终端是可以走代理的，run起来代码没报错，我在电报中对着我的bot说话，但一直收不到响应，可能啥问题呢？我确认过token没问题。

**Comment by yihong0618** [comment]
你得用特定的开头。另外需要环境变量参考 README

**Comment by zhaoxin111** [comment]
> 你得用特定的开头。另外需要环境变量参考 README

遇到了两个问题，还好问题都解决了：
1）代理网络不稳定导致有时候time out...
2）我是windows下终端启动tg的，发现通过set设置环境变量，在os.environ中就是获取不到，最后没办法，只能现在代码中手动指定API KEY.

感谢您的指点，很有趣的repo，哈哈哈
