### ISSUE TITLE
Pip install error for google-generativeai

### ISSUE THREAD

**Issue by jinwyp** [yihong0618/tg_bot_collections#4]
pip install -r requirements.txt

get error below：

ERROR: Ignored the following yanked versions: 0.1.0rc2
ERROR: Could not find a version that satisfies the requirement google-generativeai==2.25.2 (from versions: 0.1.0rc1, 0.1.0rc3, 0.1.0, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.3.1)
ERROR: No matching distribution found for google-generativeai==2.25.2

这个库 https://pypi.org/project/google-generativeai/
目前版本是 0.3.1  怎么requirements.txt 写的是2.25.2？

**Comment by yihong0618** [comment]
谢谢

**Comment by yihong0618** [comment]
@jinwyp 修复了，我傻逼了，写的是 auth 的版本感谢

**Comment by memocampos** [comment]
update google-generativeai 0.3.2 & make sure your Python version is > 3.9
